create table public.author (
                               id bigint generated by default as identity not null,
                               name text not null,
                               created_at timestamp with time zone not null default now(),
                               constraint author_pkey primary key (id)
) TABLESPACE pg_default;

create table public.publisher (
                                  id bigint generated by default as identity not null,
                                  name text not null default ''::text,
                                  created_at timestamp with time zone not null default now(),
                                  constraint publisher_pkey primary key (id)
) TABLESPACE pg_default;

create table public.book (
                             id bigint generated by default as identity not null,
                             created_at timestamp with time zone not null default now(),
                             title character varying not null,
                             isbn character varying not null,
                             year smallint not null,
                             publisher_id bigint not null,
                             constraint book_pkey primary key (id),
                             constraint book_isbn_key unique (isbn),
                             constraint book_publisher_id_fkey foreign KEY (publisher_id) references publisher (id)
) TABLESPACE pg_default;

create table public.author_books (
                                     id bigint generated by default as identity not null,
                                     author_id bigint not null,
                                     book_id bigint not null,
                                     created_at timestamp with time zone not null default now(),
                                     constraint author_books_pkey primary key (id),
                                     constraint author_books_author_id_fkey foreign KEY (author_id) references author (id),
                                     constraint author_books_book_id_fkey foreign KEY (book_id) references book (id)
) TABLESPACE pg_default;